version: '3.8'

services:
  billing_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing_automation
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
